### ISSUE TITLE
IE11 対応

### ISSUE THREAD

**Issue by koi-chan** [bcdice/api-status#11]
* そのままでは Math が使えない
  - https://qiita.com/moriyuu/items/061de38704687fef93b9
* function のデフォルト引数値に対応していない

**Comment by ysakasin** [comment]
個人的にはそもそもIE11対応をするメリットが見つけられないので、しなくてもいいのではないかと思ってます。

**Comment by koi-chan** [comment]
BCDice-API 利用者に IE を使うことが少なそう (BCDice-API を使うウェブアプリがそもそも IE で動かないなど) なため、IE のサポートは行なわないことにします。
